@startuml diagram
title "PlantUML Docker"

frame alpine-image as alpine_image {

  file diagram.wsd
  note right
    plantuml input
  end note

  file diagram.png
  note bottom
    output image
  end note

  interface plantuml
  note left
    shell script
  end note

  package "java" as java_deps {

    file plantuml.jar
    note left
      provided by plantuml.org
    end note

    node JRE
    note left
      minimal Java Runtime Environment 
      - build by jlink  
      - dependencies found by jdeps
    end note

    JRE --> plantuml.jar :depends

  }

  diagram.wsd --> plantuml
  plantuml -- JRE
  plantuml -> diagram.png

}

@enduml