name: docker-image

on:
  push:
    branches: [ "main" ]
    paths: ["Dockerfile",".github/workflows/docker-image.yaml"]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    # Docker tags and credentials, customize!
    env:
      IMAGE_NAME: plantuml-docker
      IMAGE_VERSION: latest
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PERSONAL_TOKEN: ${{ secrets.PAT }}
      GITHUB_USER: ${{ github.actor }}
    steps:
    - uses: actions/checkout@v3
    - name: Build and tag the image
      run: |
        docker build . --tag $DOCKER_USER/$IMAGE_NAME:$IMAGE_VERSION --tag ghcr.io/$GITHUB_USER/$IMAGE_NAME:$IMAGE_VERSION
    - name: Log in to DockerHub
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Publish to DockerHub
      run: |
        docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_VERSION
    - name: Log in to GitHub Container registry
      run: |
        docker login ghcr.io -u $GITHUB_USER -p $PERSONAL_TOKEN 
    - name: Pbulish to GitHub Container registry
      run: |
        docker push ghcr.io/$GITHUB_USER/$IMAGE_NAME:$IMAGE_VERSION
