name: docker-test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container: maciejskorski/plantuml-docker:naive
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Generate UM diagram
      run: plantuml src/diagram.iuml
    - name: Archive UM diagram
      uses: actions/upload-artifact@v3
      with:
        name: uml-diagram
        path: src/diagram.png
